quarkus:
  datasource:
    jdbc:
      url: jdbc:postgresql://localhost:5432/isolation
    db-kind: postgresql
    username: postgres
    password: password
  flyway:
    migrate-at-start: true
  smallrye-openapi:
    enable: true
  swagger-ui:
    enable: true
  http:
    port: 8080
#    host: 0.0.0.0
#    cors:
#      ~: true
#      origins: http://localhost:3000,http://localhost:9090
#      headers: accept, authorization, content-type, x-requested-with
#      methods: GET, OPTIONS, POST